# Site
repository: raulbanks/raulbanks.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Christopher Raul Banks
title: MUSPP Candidate 2027
email: christopher_banks@mymail.sutd.edu.sg
# email_title: Email (Email title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: raulbanks

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/MTN.jpg
about_content: | # this will include new lines to allow paragraphs
  [American Venezuelan](/images/CANAIMA.jpg) currently in the MUSPP program at SUTD.
  
  <mark>Interested in infrastructure resilience.</mark>


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Rapid Product Description Creation
        quote: >
          Turning around 4,000 production descriptions in 36 hours
        description: | # this will include new lines to allow paragraphs           
          Company CEO wanted to implement a new product labeling practice across multiple brick and mortar locations. The system proved inoperable in its present state. I used AI to write a Python script to generate descriptions for products, which was then manually reviewed and integrated into the new system.

          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Cask
        sub_title: General Manager
        caption: October 2022 -  November 2025
        quote: >
          A premier retailer of speciality spirits serving the San Francisco Bay Market
        description: | # this will include new lines to allow paragraphs          
          Lead daily operations for a specialty retail shop and bar. Manage a six-person team, 180+ vendors, and a rotating inventory in the hundreds of thousands of dollars, and millions in sales.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: College of Charleston
        sub_title: BA Political Science
        caption: 2011
        quote: >
        description: | # this will include new lines to allow paragraphs
          BA in Political Science, with a focus on International Relations
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      My spouse and I moved to Singapore in 2025 to follow a professional opportunity. I am taking this opportunity to learn about the Urban Planning practices utilized here, especially as it pertains to infrastructure resilience and system design.

      My academics have focused on Social Sciences, and my professional arc has emphasized operations, building and growing teams, managing director and vendor relationships, and always viewing situations through a systems lens.

      - [A Link to an iconic Venezulean treat](https://en.wikipedia.org/wiki/Teque%C3%B1o)
      - A Photo I took hiking in France in the morning when the sheep were passing by. 
        
        ![alt text](/images/mtnsheep.jpg)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
