# Site
repository: raulbanks/raulbanks.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Christopher Raul Banks
title: MUSPP Candidate 2027
email: christopher_banks@mymail.sutd.edu.sg
# email_title: Email (Email title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: raulbanks

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/crbmtn.jpg
about_content: | # this will include new lines to allow paragraphs
  [American Venezuelan](/images/CANAIMA.jpg) currently in the MUSPP program at SUTD.
  <mark>Interested in infrastructure resilience.</mark>

  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
    - Lists
    - Tables
    - <a href="https://google.com">Links</a>
    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Operation Fast Title
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Turning around 4,000 production descriptions in 36 hours
        description: | # this will include new lines to allow paragraphs           Company CEO wanted to implement a new product labeling practice across multiple brick and mortar locations. The syste[...]

          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Cask
        sub_title: General Manager
        caption: October 2022 -  November 2025
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs          Lead daily operations for a specialty retail shop and bar. Manage a six-person team, 180+ vendors, and 4,300+ product [...]

          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: College of Charleston
        sub_title: BA Political Science
        caption: 2011
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          BA in Political Science, with a focus on International Relations
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      My spouse and I moved to Singapore in 2025 to follow a professional opportunity. I am taking this opportunity to learn about the Urban Planning practices utilized here, especially as it pertains to infrastructure resilience.

      My academics have focused on Social Sciences, and my professional arc has emphasized operations, building and growing teams, managing director and vendor relationships, and always viewing situations from a systems perspective.

      - [A Link to an iconic Venezulean treat](https://en.wikipedia.org/wiki/Teque%C3%B1o)
      - A Photo I took hiking in France in the morning when the sheep were passing by. 
        
        ![alt text](/images/mtnsheep.jpg)

        Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
